In [35]:
from sklearn import datasets, svm, metrics
import csv
from os import rename, listdir, makedirs
from os.path import isfile, join
import os
import random
from shutil import copyfile
import glob
import pandas as pd
from numpy import genfromtxt
from IPython.display import Image, display
from StringIO import StringIO
import cv2
from sklearn.feature_extraction import image
import numpy as np
#from PIL import Image
import Image
from svgpathtools import svg2paths, wsvg
from sklearn import linear_model

In [2]:
all_images = [f for f in listdir("./all_images/") if isfile(join("./all_images/", f))]
labels = pd.read_csv("pics3_labeling-100v2.csv")

In [3]:
matrix = genfromtxt('matrix.csv', delimiter=',').T

In [4]:
np.shape(matrix)

(100, 4000)

In [5]:
#display(Image(filename="./all_images/"+all_images[0]))

In [53]:
X = np.zeros(np.shape(matrix))
all_names = labels["Name"]
isMale = labels["teeth"]
img_to_label = {}
for i in range(len(all_names)):
    name_i = all_names[i]
    for j in range(len(all_images)):
        name_j = all_images[j]
        if name_i[:len(name_i)-1]==name_j[:len(name_j)-9]:
            if isMale[i]=="Y":
                img_to_label[name_j] = True
            else:
                img_to_label[name_j] = False

In [54]:
img_to_label

{'Agnes_Bruckner_0001.jpg': False,
 'Ahmed_Lopez_0001.jpg': False,
 'Albert_Montanes_0001.jpg': True,
 'Alejandro_Toledo_0001.jpg': False,
 'Alex_Holmes_0001.jpg': True,
 'Ali_Bin_Hussein_0001.jpg': True,
 'Andrew_Niccol_0001.jpg': False,
 'Antonio_Palocci_0001.jpg': False,
 'Arnold_Palmer_0001.jpg': False,
 'Arnoldo_Aleman_0001.jpg': False,
 'Arye_Mekel_0001.jpg': False,
 'Biljana_Plavsic_0001.jpg': False,
 'Bob_Ferguson_0001.jpg': True,
 'Brenda_Wilson_0001.jpg': True,
 'Bruce_Weber_0001.jpg': True,
 'Cathryn_Crawford_0001.jpg': False,
 'Cesar_Gaviria_0001.jpg': False,
 'Daniel_Osorno_0001.jpg': True,
 'Daniele_Hypolito_0001.jpg': True,
 'Daryl_Jones_0001.jpg': True,
 'David_Obey_0001.jpg': False,
 'Desmon_Farmer_0001.jpg': True,
 'Diana_Ross_0001.jpg': False,
 'Dominik_Garcia-Lorido_0001.jpg': True,
 'Don_Carcieri_0001.jpg': True,
 'Doug_Racine_0001.jpg': False,
 'Emily_Mortimer_0001.jpg': False,
 'Fernando_Sanz_0001.jpg': False,
 'Fidel_Castro_Daiz-Balart_0001.jpg': False,
 'Floren

In [55]:
Y = []
image_path = []
count = 0
for i in img_to_label:
    Y.append(img_to_label[i])
    image_path.append("./all_images/"+i)
    count+=1

In [56]:
clf = svm.SVC()
clf.fit(X[0:30], Y[0:30])  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [57]:
# training 
print(sum(clf.predict(X[0:30]) == Y[0:30])/float(len(Y[0:30])))

# test
print(sum(clf.predict(X[31:100]) == Y[31:100])/float(len(Y[31:100])))

0.6
0.63768115942


In [58]:
clf.predict(X[31:100])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False], dtype=bool)

In [59]:
logreg = linear_model.LogisticRegression(C=1e5)

In [64]:
logreg.fit(X[0:50], Y[0:50])

LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [65]:
# training 
print(sum(logreg.predict(X[0:50]) == Y[0:50])/float(len(Y[0:50])))

# test
print(sum(logreg.predict(X[51:100]) == Y[51:100])/float(len(Y[51:100])))

0.64
0.612244897959


In [66]:
logreg.predict(X[31:100])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False], dtype=bool)

In [68]:
logreg.predict(X[0:50])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False], dtype=bool)